### ISSUE TITLE
Worker Profiler base URL path

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#151]
### Summary
Make Worker Profiler work with a configurable base URL path so all its URLs become relative to that. E.g. if the configured URL is `base`, then `/` becomes `/base/`, `/WorkerProfiler` becomes `/base/WorkerProfiler`, and so on.

### Intended outcome
This feature would make Worker Profiler work nicely with Kitt4sme's path-based routing of incoming HTTP traffic. Users could access the app at http://kitt4sme.host/profiler instead of having to use a port as it happens now---e.g. http://kitt4sme.collab-cloud.eu:7777.

 This should be possible simply by configuring Worker Pro's K8s deployment with a `BASE_PATH` env var set to `profiler` and
 the Istio routing config below

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "kitt4sme-virtual-service"
# ...
spec:
# ...
  http:
# ...
  - match:
    - uri:
        prefix: /profiler
    route:
    - destination:
        host: workerpro.default.svc.cluster.local
        port:
          number: 7777
```

As an added benefit, we can get rid of the current K8s node port through which Worker Pro can be reached from outside the cluster, which is going to make it much easier to secure the service, do load balancing, etc.

### How will it work?
Well, as usual there's more than one way to skin a cat. But here's an approach. On start up The app reads the value of the `BASE_PATH` env var and tells ASP.NET to use it:

```c#
//  read the value of `BASE_PATH` into `baseFromEnv`, then make this call
app.UsePathBase(baseFromEnv);
// ...
app.UseRouting();
```

That variable should be declared in the Docker file too.

See also:
- https://stackoverflow.com/questions/56055697
- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0#work-with-path-base-and-proxies-that-change-the-request-path
- https://stackoverflow.com/questions/60546843
