### ISSUE TITLE
Adaptive Questionnaire faulty SSO redirect

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#310]
### Describe the bug
#307 configured AQ for SSO with RAMP. It seems to work fine in some cases but in others we get a nasty redirect to a dead-end URL after login.

### To Reproduce
1. Start a browser in incognito mode.
2. Browse to AQ: https://kitt4sme.collab-cloud.eu/aq
3. You should get redirected to RAMP (https://ramp.eu/) where a login form should display
4. Login with the RAMP test user `man@test.com` and password the RAMP guys gave you
5. After successfully logging in, your browser should be redirected to a nonsensical URL similar to this---notice the port of `0`: https://kitt4sme.collab-cloud.eu:0/aq/sso/login?state=1f42469e-67ad-4b85-9025-8356ff089d16&session_state=447c1893-ce2a-4951-9b85-b42c130155f7&code=96caf1ac-d256-4e12-8ebf-9743cca1a94a.447c1893-ce2a-4951-9b85-b42c130155f7.750cae43-f2b4-4082-8119-bdcf8cccc427
6. But now if you browse again to AQ (https://kitt4sme.collab-cloud.eu/aq), you should be able to get in and see the start page.

### Expected behavior
If you aren't logged into RAMP and browse to AQ, you should get redirected to the RAMP login form. After successfully logging into RAMP, you should get redirected back to AQ's start page.

### Additional context
See also: #307

**Comment by RyanKelvinFord** [comment]
I have just retested this and the problem is still there, I will start investigating it.

**Comment by RyanKelvinFord** [comment]
I will look into how the authentication is managed however first assumption would be some issue with the keycloak integration

**Comment by RyanKelvinFord** [comment]
Have not had time to continue with this as there is some extraction work required for the datasheets tool

**Comment by RyanKelvinFord** [comment]
Could someone from RAMP not confirm the configuration of this?

**Comment by vcutrona** [comment]
While trying to reproduce this issue (using Chrome `Version 117.0.5938.88 (Official Build) (64-bit)` on Ubuntu 22.04, Incognito mode), I got the following error:

ERR_TOO_MANY_REDIRECTS

I've been redirected to https://kitt4sme.collab-cloud.eu/aq/sso/login?state=a2c2c6ed-0932-4b54-8fbd-bdfa83693cb1&session_state=74335a47-a4ae-4346-be53-d806ac6fa6eb&code=96abe796-915b-4e80-b5d6-f0f59e75bc04.74335a47-a4ae-4346-be53-d806ac6fa6eb.750cae43-f2b4-4082-8119-bdcf8cccc427

**Comment by pmpoukli** [comment]
Just tested SSO with digital datasheets and works fine. The redirection happens within the collab-cloud server. Have you set up the SSO with Keycloak client?

**Comment by vcutrona** [comment]
this is the current configuration we use for AQ:

```yaml
        - name: KEYCLOAK_REALM
          value: "kitt4sme"
        - name: KEYCLOAK_AUTH_SERVER_URL
          value: "https://kitt4sme.collab-cloud.eu/auth"
        - name: KEYCLOAK_RESOURCE
          value: "aq"
        - name: KEYCLOAK_CREDENTIALS_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-clients
              key: aq.oidc.client.secret
```
RAMP is registered as an Identity Provider in Keycloak
